In [2]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join("..", "data", "house_tiny.csv")

with open(data_file, 'w') as f:
    f.write("NumRooms, Alley, Price\n")
    f.write("NA, Pave, 127500\n")
    f.write("2,NA,106000\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,140000\n")
    

In [3]:
import pandas as pd
data = pd.read_csv(os.path.join("..", "data", "house_tiny.csv"))
print(data)

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN  106000
2       4.0    NaN  178100
3       NaN    NaN  140000


In [4]:
import torch
x = torch.arange(20).reshape(5, 4)

In [5]:
x
x.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [11]:
B = torch.tensor([[1, 2, 3], [2,0,4], [3, 4, 5]])
B

A = torch.arange(9).reshape(3, 3)

A
A*B

tensor([[ 0,  2,  6],
        [ 6,  0, 20],
        [18, 28, 40]])

In [12]:
a = torch.ones([2, 5, 4])
a.shape

torch.Size([2, 5, 4])

In [16]:
a.sum().shape
a.sum(axis=1).shape
a.sum(axis=2).shape
a.sum(axis=0).shape

torch.Size([5, 4])

In [18]:
A = torch.rand(2, 5)
A.shape
A

tensor([[0.9088, 0.8009, 0.1684, 0.0296, 0.5991],
        [0.5647, 0.1612, 0.0448, 0.4050, 0.8085]])

In [20]:
torch.cuda.device_count()

0