In [1]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
x.shape

torch.Size([12])

In [3]:
x.numel()

12

In [4]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
x1 = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x1+y, x1-y, x1*y, x1/y, x1**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [6]:
torch.cat((x1,y), dim=0)

tensor([1., 2., 4., 8., 2., 2., 2., 2.])

In [7]:
x1 == y

tensor([False,  True, False, False])

In [8]:
x.sum()

tensor(66)

In [9]:
x[0:1]

tensor([0])

In [10]:
x[0:4]

tensor([0, 1, 2, 3])

In [11]:
x[5] = 2

In [12]:
x


tensor([ 0,  1,  2,  3,  4,  2,  6,  7,  8,  9, 10, 11])